### PR TITLE
Fix Ambiguous Column Errors

### LINKED ISSUE #39: Ambiguous column error when filtering on query with joins
When attempting to filter a query with joins on inserted_at I get a `(Postgrex.Error) ERROR 42702 (ambiguous_column): column reference "inserted_at" is ambiguous` as the fragment doesn't specify which table it's referencing.

### PR DESCRIPTION
**Pull request by danielberkompas**
As mentioned in #39, if you try to use Filtrex with a query that
includes joins, you will sometimes get "Ambiguous column errors".

This happens because Filtrex does not properly scope its filters. This
PR makes Filtrex scope its queried fields to the primary table being
queried.

Closes #39.

### CODE REVIEW

File: lib/filtrex/utils/encoder.ex [hunk 1]
```diff
@@ -20,17 +20,33 @@ defmodule Filtrex.Utils.Encoder do
...
+          values: values
         }
       end
     end
   end
 
+  def intersperse_column_refs(values, column) do
+    column = String.to_existing_atom(column)
+
+    [quote do: s.unquote(column)]
```
Comment (rcdilorenzo) [inline lib/filtrex/utils/encoder.ex]: Forgive my ignorance, but how do we actually reference the schema table by using `s` here. Is this something we are assuming from Ecto?

File: lib/filtrex/utils/encoder.ex [hunk 2]
```diff
@@ -20,17 +20,33 @@ defmodule Filtrex.Utils.Encoder do
...
-          expression: String.replace(unquote(expression), "column", column),
-          values: unquote(values_function).(value)
+          expression: String.replace(unquote(expression), "column", "?"),
+          values: values
         }
       end
     end
   end
 
+  def intersperse_column_refs(values, column) do
```
Comment (rcdilorenzo) [inline lib/filtrex/utils/encoder.ex]: This function seems reasonable to me but it should either have a `docstring`, be private, or be embedded into the macro `quote` block.

File: test/conditions/boolean_test.exs [hunk 3]
```diff
@@ -26,18 +27,18 @@ defmodule FiltrexConditionBooleanTest do
 
   test "encoding true value" do
     assert Filtrex.Encoder.encode(condition(true, "equals")) ==
-      %Filtrex.Fragment{expression: "flag = ?", values: [true]}
+      %Filtrex.Fragment{expression: "? = ?", values: [column_ref(:flag), true]}
```
Comment (rcdilorenzo) [inline test/conditions/boolean_test.exs:30]: Similar to previous question, will this result in a string or something else?

**Review by rcdilorenzo — CHANGES_REQUESTED** [review]
@danielberkompas I am supremely grateful for this pull request! :clap: It appears that you know Ecto more than I do with the column referencing you are doing. Most of my comments are questions with one minor change. Assuming those are resolved, I'll try to quickly get back to you to wrap this up.

Once again, thanks a million.

File: lib/filtrex/utils/encoder.ex (hunk 1 above)
Comment (danielberkompas) [reply lib/filtrex/utils/encoder.ex]: The answer lies here:

https://github.com/rcdilorenzo/filtrex/blob/c6980d9c5796e3a10f1d2947b4e0830926ce30b7/lib/filtrex/ast.ex#L11

This is where Filtrex assigns the primary table in the query to the alias `s`.

Comment (rcdilorenzo) [reply lib/filtrex/utils/encoder.ex]: Ah, I hate when I forget code that I wrote myself. Thanks for being patient with me. :slightly_smiling_face:

File: test/conditions/boolean_test.exs (hunk 3 above)
Comment (danielberkompas) [reply test/conditions/boolean_test.exs:30]: `column_ref` returns a macro AST for `s.column_name`.

```elixir
{{:., [], [{:s, [], Filtrex.Util.Encoder}, :column_name]}, [], []}
```

The `AST` module unquotes these `values` into the final Ecto query fragment macro, resulting in `s.column_name`.

File: lib/filtrex/utils/encoder.ex (hunk 2 above)
Comment (danielberkompas) [reply lib/filtrex/utils/encoder.ex]: I'll give it a `@doc` tag. I didn't put it into the macro `quote` block because it doesn't use anything from the generated module's context. When a functional solution works, I tend to use it instead of macros.

Comment (rcdilorenzo) [reply lib/filtrex/utils/encoder.ex]: @danielberkompas Agreed. I have the same perspective about embedding it. I think actual Jose mentioned it specifically at some point as a recommendation.

**Comment by danielberkompas** [comment]
I'm happy to contribute! I like Filtrex a lot, and we use it in many of our client projects at [Infinite Red](https://github.com/infinitered). We ship it with [Torch](https://github.com/infinitered/torch). Great work on a very useful tool!

**Review by rcdilorenzo — APPROVED** [review]
